const Meta = () => {
  return (
    <>
      <title>3rd Space AI</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="icon" type="image/png" href="/favicon.png"></link>
    </>
  );
};
export default Meta;
